=== Deux12/Lenguaje-de-marcas/Leguajes de marcas/Preguntas examen Dani/personas.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="personas">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="nombre" type="xsd:string" />
                <xsd:element ref="nacimiento" />
                <xsd:element ref="direccion" />
                <xsd:element name="sexo" type="tipoSexo" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="direccion">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="calle" type="xsd:string"/>
                <xsd:element name="poblacion" type="xsd:string"/>
                <xsd:element name="provincia" type="xsd:string"/>
                <xsd:element name="cpostal" type="xsd:positiveInteger"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="tipoSexo">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Varon" />
            <xsd:enumeration value="Hembra" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="nacimiento">
        <xsd:complexType>
            <xsd:attribute name="dia" type="tipoDia" />
            <xsd:attribute name="mes" type="tipoMes" />
            <xsd:attribute name="anyo" type="tipoAnyo" />
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="tipoDia">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="31" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoMes">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Enero" />
            <xsd:enumeration value="Febrero" />
            <xsd:enumeration value="Marzo" />
            <xsd:enumeration value="Abril" />
            <xsd:enumeration value="Mayo" />
            <xsd:enumeration value="Junio" />
            <xsd:enumeration value="Julio" />
            <xsd:enumeration value="Agosto" />
            <xsd:enumeration value="Septiembre" />
            <xsd:enumeration value="Octubre" />
            <xsd:enumeration value="Noviembre" />
            <xsd:enumeration value="Diciembre" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoAnyo">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1900" />
            <xsd:maxInclusive value="2011" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== Deux12/Lenguaje-de-marcas/Leguajes de marcas/Preguntas examen Dani/ejercioTipoExamen2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<personas  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="personas.xsd">
    <nombre>Juan Pardo</nombre>
    <nacimiento dia="10" mes="Abril" anyo="1982" />
    <direccion>
        <calle>caoba,1</calle>
        <poblacion>Madrid</poblacion>
        <provincia>Madrid</provincia>
        <cpostal>28005</cpostal>
    </direccion>
    <sexo>Varon</sexo>
</personas>
